name: Build and Push Docker Image with Jib

on:
  push:
    branches: ["Feat/CLO-193-jenkins"]
permissions:
  contents: read

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository and Submodules
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.ACTIONS_TOKEN }}

      - name: Copy application.yml from submodule
        run: |
          mkdir -p src/main/resources
          cp application-config/application-prod.yml src/main/resources/application-prod.yml

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build and push Docker image
        run: |
          ./gradlew clean jib \
            -Djib.to.tags=${{ github.sha }} \
            -Djib.to.auth.username=${{ secrets.KAKAO_ACCESS_ID }} \
            -Djib.to.auth.password=${{ secrets.KAKAO_ACCESS_SECRET }}