name: Java CICD with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build-docker-image:
    runs-on: centos-9
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: clean bootJar

    - name: docker image build
      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/clovider-be-app .

    - name: docker login
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: docker Hub push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/clovider-be-app
  deploy:
    name: Deploy to GCP Compute Engine
    runs-on: centos-9
    needs: build-docker-image

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.GCP_COMPUTE_ENGINE_SSH_KEY }}

      - name: Pull Docker image from Docker Hub
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.GCP_COMPUTE_ENGINE_SSH_USER }}@${{ secrets.GCP_COMPUTE_ENGINE_INSTANCE }} \
            "docker pull ${{ secrets.DOCKERHUB_USERNAME }}/clovider-be-app"
      - name: Run Docker container on GCP
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.GCP_COMPUTE_ENGINE_SSH_USER }}@${{ secrets.GCP_COMPUTE_ENGINE_INSTANCE }} \
            "docker run -d --rm -p 8080:8080 ${{ secrets.DOCKERHUB_USERNAME }}/clovider-be-app"
