name: CLOVIDER Backend CI/CD Pipeline

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Set environment yml file
        run: echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.yml
        shell: bash
  
      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: clean bootJar
          
      - name: 카카오 컨테이너 레지스트리에 로그인중...
        run: |
          docker login kids-in-company.kr-central-2.kcr.dev --username ${{ secrets.KAKAO_ACCESS_ID }} --password ${{ secrets.KAKAO_ACCESS_SECRET }}

      - name: Docker 이미지 빌드중..
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile
          context: .
          push: false
          tags: clovider-be-app:latest

      - name: Docker 이미지 태그 설정중..
        run: |
          docker tag clovider-be-app:latest kids-in-company.kr-central-2.kcr.dev/clovider-registry/clovider-be-app:latest

      - name: 카카오 컨테이너 레지스트리에 푸시중..
        run: |
          docker push kids-in-company.kr-central-2.kcr.dev/clovider-registry/clovider-be-app:latest
