name: CLOVIDER Backend CI/CD Pipeline

on:
  push:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository and Submodules
        uses: actions/checkout@v3
        with:
          submodules: true
          token: ${{ secrets.ACTIONS_TOKEN }}

      - name: Copy application.yml from submodule
        run: |
          mkdir -p src/main/resources
          cp application-config/application.yml src/main/resources/application.yml
          cp application-config/application-dev.yml src/main/resources/application-dev.yml
          cp application-config/application-prod.yml src/main/resources/application-prod.yml

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: clean bootJar

      - name: Login to Kakao Container Registry
        run: |
          echo ${{ secrets.KAKAO_ACCESS_SECRET }} | docker login kids-in-company.kr-central-2.kcr.dev --username ${{ secrets.KAKAO_ACCESS_ID }} --password-stdin
          
      - name: Build and Push Docker Image
        run: |
          docker build -t kids-in-company.kr-central-2.kcr.dev/clovider-registry/clovider-be-app:${{ github.sha }} .
          docker push kids-in-company.kr-central-2.kcr.dev/clovider-registry/clovider-be-app:${{ github.sha }}

  update-manifest-state:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:
      - name: Checkout kic-k8s Repository
        uses: actions/checkout@v3
        with:
          repository: ${{ secrets.GIT_PROJECT }}/kic-k8s
          token: ${{ secrets.ACTIONS_TOKEN }}
          ref: "main"

      - name: Install yq
        run: sudo snap install yq

      - name: Update image tag in deployment file
        run: |
          yq e ".spec.template.spec.containers[0].image = \"kids-in-company.kr-central-2.kcr.dev/clovider-registry/clovider-be-app:${{ github.sha }}\"" -i clovider-app/be-deployment.yaml

      - name: Commit and Push changes
        run: |
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "${{ secrets.USERNAME }}"
          git add clovider-app/be-deployment.yaml
          git commit -m "[skip ci] Update image tag to ${{ github.sha }}"
          git push
